#!/usr/bin/bash
apt install git -y
git clone https://github.com/wizardoffoss/misc
git clone https://github.com/kiransbaliga/Network-Lab
git clone https://github.com/Haafii/Ktu-Networking-Lab-S6
git clone https://github.com/cechengannur/Networking-Lab-S6
